#!/bin/bash

cd ../ && \
git init $2 && \
cd $2 && \
git remote add origin $3 && \
git remote add template git://github.com/winton/node_template.git && \
git fetch template && \
git merge template/master && \
cake install && \
echo -e "\n\033[1;32mSuccess!\033[0m" && \
echo -e "\n\033[1;33mStart your server:\033[0m cd ../$2 && cake start\n"